[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
build       = "build.rs"
description = "Substrate node compatible with Millau runtime"
edition     = "2018"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "millau-bridge-node"
repository  = "https://github.com/darwinia-network/darwinia-launch"
version     = "0.1.0"

[dependencies]
# crates.io
jsonrpc-core = { version = "15.1.0" }
serde_json   = { version = "1.0.64" }
structopt    = { version = "0.3.21" }
# bridge
bp-messages                = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
bp-millau                  = { path = "../chain-millau" }
bp-runtime                 = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
millau-runtime             = { path = "../runtime" }
pallet-bridge-messages     = { git = "https://github.com/darwinia-network/parity-bridges-common", branch = "s2s" }
pangolin-bridge-primitives = { git = "https://github.com/darwinia-network/darwinia-common", branch = "s2s" }
# substrate
node-inspect                   = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
pallet-transaction-payment-rpc = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-basic-authorship            = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-cli                         = { features = ["wasmtime"], git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-client-api                  = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-consensus                   = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-consensus-aura              = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-executor                    = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-finality-grandpa            = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-finality-grandpa-rpc        = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-keystore                    = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-rpc                         = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-service                     = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-telemetry                   = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sc-transaction-pool            = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-consensus                   = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-consensus-aura              = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-core                        = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-finality-grandpa            = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-inherents                   = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-runtime                     = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
sp-timestamp                   = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }
substrate-frame-rpc-system     = { git = "https://github.com/darwinia-network/substrate", branch = "s2s" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0" }
